(source (git https://github.com/oxidizing/spin-sihl.git))
(config username "Kiran Gopinathan")
(config project_name activitypub-server)
(config docker No)
(config github_username gopiandcode)
(config project_description
 "A simple single user activitypub federated server instance")
(config ci_cd Github)
(config project_snake activitypub_server)
(config database PostgreSql)
(config project_slug activitypub-server)
(config create_switch No)
