(let (kword-start kword-end fn-name)
         (search-forward "val")
         (backward-word)
         (kill-word nil)
         (forward-word)
         (backward-word)
         (insert "\"")
         (setq kword-start (point))
         (forward-sexp)
         (setq fn-name (buffer-substring-no-properties kword-start (point)))
         (insert "\"")
         (setq kword-end (point))
         (search-forward ":")
         (delete-region kword-end (point))
         (forward-word) (backward-word))
